// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDygXchTO0m38aMhyc7rvqB3_0USlO_sEE',
    appId: '1:544950182249:web:8981814794bdd37f179df8',
    messagingSenderId: '544950182249',
    projectId: 'mytask-2bc5a',
    authDomain: 'mytask-2bc5a.firebaseapp.com',
    storageBucket: 'mytask-2bc5a.appspot.com',
    measurementId: 'G-SSWG6MZQ1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnr7Sb3pRJrgAy6fcE73PcvDIBZigTWHQ',
    appId: '1:544950182249:android:8f2b4cd2043ffd78179df8',
    messagingSenderId: '544950182249',
    projectId: 'mytask-2bc5a',
    storageBucket: 'mytask-2bc5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh5ZqNQKXhNXl53MbydYDNSEsuYrw5Edk',
    appId: '1:544950182249:ios:74abd37b3b5aff1c179df8',
    messagingSenderId: '544950182249',
    projectId: 'mytask-2bc5a',
    storageBucket: 'mytask-2bc5a.appspot.com',
    iosBundleId: 'com.example.mytask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh5ZqNQKXhNXl53MbydYDNSEsuYrw5Edk',
    appId: '1:544950182249:ios:b1d2844c6d53cca7179df8',
    messagingSenderId: '544950182249',
    projectId: 'mytask-2bc5a',
    storageBucket: 'mytask-2bc5a.appspot.com',
    iosBundleId: 'com.example.mytask.RunnerTests',
  );
}
